name = "backend"
compatibility_date = "2024-08-22"

[vars]

DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTc4ODg1YjktNWM4NS00MTg0LWE1NTQtYjAwN2E2OTQ5ZjhjIiwidGVuYW50X2lkIjoiZjZkNjgxMWFlZjU5YTJjZTI5ZjEwNGMxOWIwNDA3ZWM5NmY0N2UyYTJkNzYwNmJjNDA3NmQ0ZjRiMzI3NzMyMCIsImludGVybmFsX3NlY3JldCI6ImI4NmVjODk2LWJmODYtNDBmZC1hZTMzLTg3MzhiODI2MGMwNSJ9.FLcsOVUsM1IkhhsukFSLwpB7YadfS7US1SI_QXJYEmc"
JWT_SECRET = "123456" 
